[package]
name = "raui"
version = "0.24.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "Renderer Agnostic User Interface"
readme = "README.md"
license = "MIT"
repository = "https://github.com/PsichiX/raui"
keywords = ["renderer", "agnostic", "ui", "interface", "gamedev"]
categories = ["gui", "rendering::graphics-api"]
exclude = [
  ".github/**",
  "demos/**",
  "media/**",
]

[features]
scalar64 = ["raui-core/scalar64"]
integer64 = ["raui-core/integer64"]
material = ["raui-material"]
binary = ["raui-binary-renderer"]
html = ["raui-html-renderer"]
json = ["raui-json-renderer"]
ron = ["raui-ron-renderer"]
yaml = ["raui-yaml-renderer"]
all = [
  "material",
  "binary",
  "html",
  "json",
  "ron",
  "yaml",
]

[dependencies]
raui-core = { path = "./raui-core", version = "0.24" }

[dependencies.raui-material]
path = "./raui-material"
version = "0.24"
optional = true

[dependencies.raui-binary-renderer]
path = "./raui-binary-renderer"
version = "0.24"
optional = true

[dependencies.raui-html-renderer]
path = "./raui-html-renderer"
version = "0.24"
optional = true

[dependencies.raui-json-renderer]
path = "./raui-json-renderer"
version = "0.24"
optional = true

[dependencies.raui-ron-renderer]
path = "./raui-ron-renderer"
version = "0.24"
optional = true

[dependencies.raui-yaml-renderer]
path = "./raui-yaml-renderer"
version = "0.24"
optional = true

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"

[workspace]
members = [
  "raui-core",
  "raui-capi",
  "raui-binary-renderer",
  "raui-ggez-renderer",
  "raui-html-renderer",
  "raui-json-renderer",
  "raui-material",
  "raui-ron-renderer",
  "raui-yaml-renderer",
  "demos/hello-world",
  "demos/todo-app",
  "demos/in-game",
]
