name: Rust

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --verbose --exclude hello-world in-game todo-app
    - name: Run tests
      run: cargo test --all --features all --verbose --exclude hello-world in-game todo-app
